Repository lcompilers/lpython, pull requests merged in 2022-10, with the labels that each got.

#1168 C: Fix functions with string return type
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_c_cpp.h
Labels: c

#1172 C: Implement Character to Integer Cast
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_c_cpp.h
  src/libasr/codegen/asr_to_llvm.cpp
Labels: c

#1119 Implement list_concat ASR pass
  integration_tests/CMakeLists.txt
  integration_tests/test_list_09.py
  src/libasr/CMakeLists.txt
  src/libasr/pass/pass_list_concat.cpp
  src/libasr/pass/pass_list_concat.h
  src/libasr/pass/pass_manager.h
Labels: asr_pass

#1112 Support String Repeat func C backend
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_c_cpp.h
  src/libasr/runtime/lfortran_intrinsics.c
  src/libasr/runtime/lfortran_intrinsics.h
Labels: ready for review

#1169 C: Implement nested Lists
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_c_cpp.h
Labels: ready for review, c

#1184 Implement List Section in the ASR Pass
  integration_tests/CMakeLists.txt
  integration_tests/test_list_10.py
  src/libasr/CMakeLists.txt
  src/libasr/pass/pass_list_concat.cpp
  src/libasr/pass/pass_list_concat.h
  src/libasr/pass/pass_list_expr.cpp
  src/libasr/pass/pass_list_expr.h
  src/libasr/pass/pass_manager.h
Labels: ready for review, asr_pass

#1193 Tokenize Match and Case Keywords and fix remaining issues
  src/lpython/parser/parser.yy
  src/lpython/parser/tokenizer.h
  src/lpython/parser/tokenizer.re
  tests/parser/match_stmt1.py
  tests/reference/ast_new-match_stmt1-9e84d24.json
  tests/reference/ast_new-match_stmt1-9e84d24.stdout
Labels: ready for review, Parser

#1191 C: Implement List Concat
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_c_cpp.h
Labels: c

#1083 Implement numpy.floor and numpy.ceil functions
  integration_tests/CMakeLists.txt
  integration_tests/elemental_12.py
  src/runtime/lpython_intrinsic_numpy.py
  tests/reference/asr-array_01_decl-39cf894.json
  tests/reference/asr-array_01_decl-39cf894.stdout
  tests/reference/asr-array_02_decl-e8f6874.json
  tests/reference/asr-array_02_decl-e8f6874.stdout
  tests/reference/asr-elemental_01-b58df26.json
  tests/reference/asr-elemental_01-b58df26.stdout
  tests/reference/asr-generics_array_01-682b1b2.json
  tests/reference/asr-generics_array_01-682b1b2.stdout
  tests/reference/asr-generics_array_02-22c8dc1.json
  tests/reference/asr-generics_array_02-22c8dc1.stdout
  tests/reference/asr-generics_array_03-fb3706c.json
  tests/reference/asr-generics_array_03-fb3706c.stdout
  tests/reference/asr-test_numpy_03-e600a49.json
  tests/reference/asr-test_numpy_03-e600a49.stdout
  tests/reference/asr-test_numpy_04-ecbb614.json
  tests/reference/asr-test_numpy_04-ecbb614.stdout
  tests/reference/asr-vec_01-66ac423.json
  tests/reference/asr-vec_01-66ac423.stdout
  tests/reference/pass_loop_vectorise-vec_01-be9985e.json
  tests/reference/pass_loop_vectorise-vec_01-be9985e.stdout
Labels: ready for review

#1202 ASR: Refactor string attribute frontend
  src/lpython/semantics/python_ast_to_asr.cpp
Labels: ready for review, asr

#1207 C: Add Tuple support
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_c.cpp
  src/libasr/codegen/asr_to_c_cpp.h
  src/libasr/codegen/asr_to_cpp.cpp
  src/libasr/codegen/c_utils.h
Labels: c

#1185 Compile Simple Python package
  integration_tests/CMakeLists.txt
  integration_tests/test_import/__init__.py
  integration_tests/test_import/test_import_1.py
  integration_tests/test_import/test_import_2.py
  integration_tests/test_import_01.py
  src/bin/lpython.cpp
  src/libasr/utils.h
  src/lpython/semantics/python_ast_to_asr.cpp
  src/lpython/semantics/python_ast_to_asr.h
  src/lpython/utils.cpp
  src/lpython/utils.h
Labels: ready for review

#1180 Add runtime tests support
  .github/workflows/CI.yml
  run_tests.py
  src/bin/lpython.cpp
  src/libasr/codegen/asr_to_llvm.cpp
  src/libasr/codegen/llvm_utils.cpp
  src/libasr/codegen/llvm_utils.h
  src/libasr/runtime/lfortran_intrinsics.c
  src/libasr/runtime/lfortran_intrinsics.h
  src/libasr/utils.h
  tests/reference/llvm-assert1-8df4f31.json
  tests/reference/llvm-assert1-8df4f31.stdout
  tests/reference/llvm-bindc_02-3cf74e9.json
  tests/reference/llvm-bindc_02-3cf74e9.stdout
  tests/reference/llvm-func_inline_01-2d4583a.json
  tests/reference/llvm-func_inline_01-2d4583a.stdout
  tests/reference/llvm-test_integer_bitnot-6894b6d.json
  tests/reference/llvm-test_integer_bitnot-6894b6d.stdout
  tests/reference/llvm-test_issue_518-cdb641a.json
  tests/reference/llvm-test_issue_518-cdb641a.stdout
  tests/reference/runtime-test_list_01-3ee9b3e.json
  tests/reference/runtime-test_list_01-3ee9b3e.stderr
  tests/runtime_errors/test_list_01.py
  tests/tests.toml
Labels: ready for review

#1239 C: Enable `divmod` builtin
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_c_cpp.h
Labels: ready for review, c

#1241 C: Fix variable imports from module
  integration_tests/test_math1.py
  src/libasr/codegen/asr_to_c_cpp.h
Labels: ready for review, c

#1237 C: Str to List cast
  integration_tests/CMakeLists.txt
  src/runtime/lpython_builtin.py
Labels: ready for review, c

#1216 Enable more C tests
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_c_cpp.h
  src/libasr/runtime/lfortran_intrinsics.c
  src/libasr/runtime/lfortran_intrinsics.h
  src/runtime/lpython_builtin.py
Labels: ready for review, c

#1243 ASR: Allow variable access from module using dot
  integration_tests/test_math.py
  src/lpython/semantics/python_ast_to_asr.cpp
Labels: bug, ready for review, asr

#1240 Initial debugging info implementation
  run_tests.py
  src/bin/lpython.cpp
  src/libasr/codegen/asr_to_llvm.cpp
  src/libasr/codegen/asr_to_llvm.h
  src/libasr/utils.h
  src/lpython/python_evaluator.cpp
  tests/reference/llvm_dbg-expr_01-bc258d6.json
  tests/reference/llvm_dbg-expr_01-bc258d6.stdout
  tests/tests.toml
Labels: ready for review
