Repository lcompilers/lpython, pull requests merged in 2023-03, with the labels that each got.

#1444 C: Implement Dictionary
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_c.cpp
  src/libasr/codegen/asr_to_c_cpp.h
  src/libasr/codegen/c_utils.h
Labels: c

#1476 C: Generalize handing of extra codegen
  integration_tests/CMakeLists.txt
  integration_tests/print_list_tuple.py
  src/libasr/codegen/asr_to_c.cpp
  src/libasr/codegen/asr_to_c_cpp.h
Labels: c

#1568 C: Implement Dict pop
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_c_cpp.h
  src/libasr/codegen/c_utils.h
Labels: c

#1572 C: Handle generics
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_c_cpp.h
Labels: c

#1574 C: Complete all generic tests
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_c_cpp.h
Labels: c

#1123 PASS: Improve print tuple
  integration_tests/CMakeLists.txt
  integration_tests/print_list_tuple_01.py
  integration_tests/print_list_tuple_02.py
  run_tests.py
  src/libasr/CMakeLists.txt
  src/libasr/pass/pass_manager.h
  src/libasr/pass/print_list_tuple.cpp
  src/libasr/pass/print_list_tuple.h
  tests/reference/pass_print_list_tuple-print_02-09600eb.json
  tests/reference/pass_print_list_tuple-print_02-09600eb.stdout
  tests/tests.toml
Labels: asr_pass

#1592 ASR Pass: Fix variables names to be used in C backend
  integration_tests/CMakeLists.txt
  integration_tests/loop_04.py
  integration_tests/loop_05.py
  src/libasr/pass/arr_slice.cpp
  src/libasr/pass/pass_utils.cpp
Labels: c, asr_pass

#1596 C: Enable elemental tests
  integration_tests/CMakeLists.txt
  integration_tests/elemental_03.py
  integration_tests/elemental_04.py
Labels: c

#1605 Add --backend=c to directly run with C
  .gitignore
  ci/test.xsh
  src/bin/lpython.cpp
Labels: enhancement, c

#1621 WASM: give an error message if sections are in wrong order
  src/libasr/codegen/wasm_decoder.h
Labels: wasm
